name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Test
      shell: bash
      run: |
        docker run --interactive --volume="$(pwd)":/io:Z --workdir=/io \
          archlinux/archlinux:base-devel bash <<EOF
        pacman -Syu --noconfirm &&
          pacman -S --noconfirm git namcap pkgfile python &&
          pkgfile --update &&
          chmod -R a+rwx . &&
          sudo -u nobody python -munittest &&
          pacman -S --noconfirm cython rustup &&
          sudo -u nobody python pypi2pkgbuild.py -vI --pre git+https://github.com/notofonts/notobuilder
        EOF
